add probe bof
trustedsec/CS-Situational-Awareness-BOF pull request #69
Opened 2022-03-15 21:35 UTC by rwhitcroft

Test if a remote port is open, similar to `nc -z`.

Issues:
- I defined `struct addrinfo` directly in `bofdefs.h`, but not sure this is allowed. I did this because including `<ws2tcpip.h>` results in warnings from other bofs that include `<windows.h>` before `bofdefs.h`. 
- I don't have a CS license, so I'm using Sliver for all of this. I can't test the `SA.cna` part but tried to copy the other ones.

I realize this is not a groundbreaking addition to the repo, so no big deal if it's too much of a hassle to add. I had a blast learning BOF stuff either way.

```
[server] sliver (ALTERNATIVE_STAMINA) > probe 127.0.0.1 445

[*] Successfully executed probe (coff-loader)
[*] Got output:
127.0.0.1:445 OPEN

[server] sliver (ALTERNATIVE_STAMINA) > probe 127.0.0.1 12345

[*] Successfully executed probe (coff-loader)
[*] Got output:
127.0.0.1:12345 FAILED

[server] sliver (ALTERNATIVE_STAMINA) > probe dc01.ad.local 445

[*] Successfully executed probe (coff-loader)
[*] Got output:
dc01.ad.local:445 OPEN
```

2022-03-15 23:39 UTC, freefirex commented
I'll be happy to review this and work with you on getting it merged in 😄 

Just to let you know timeline I'm teaching this week, so I'll review and provide any feedback monday or tuesday of next week.

2022-03-21 14:03 UTC, freefirex requested changes
This is very good code. I like how you handled timeout / blocking mode.  I've added the changes I'd like made to accept this in, I've tested the changes as written on my end.  

For not having access to sleep you did that side very well as well :)

Thanks again!

2022-03-21 14:03 UTC, freefirex commented on SA/SA.cna
> +// ------------------------------
Delete this line or switch to 
```suggestion
# ------------------------------
```
in cna # is used for comments

2022-03-21 14:03 UTC, freefirex commented on SA/SA.cna
> +	$port = $3;
While someone would have to try pretty hard to break this (or spaz out on the keyboard) I think adding a sanity check here so we for sure can't overflow the sprintf would be optimal.

in cna that would look like this (after adding $portint to local)
```suggestion
	$port = $3;
	$portint = parseNumber($port, 10);
	if($portint < 1 || $portint > 65535)
	{
		berror($1, "usage: probe <host> <port>");
		berror($1, "Port out of range");
		return;
	}
```

2022-03-21 14:03 UTC, freefirex commented on src/SA/probe/entry.c
> +                WS2_32$closesocket(sock);
from (https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-closesocket)[https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-closesocket]
`An application should always have a matching call to closesocket for each successful call to socket to return any socket resources to the system.`

from that we should move this closesocket call below this if statement, rather then inside it

2022-03-22 15:07 UTC, rwhitcroft commented
Thank you for the review and suggestions! I think I got them all fixed.

2022-03-23 18:31 UTC, freefirex approved these changes

2022-03-23 18:31 UTC, merged

2022-03-23 18:31 UTC, freefirex commented
Thanks for making those changes! merged